---
- hosts: k8s_gpu_nodes 
  remote_user: root

  tasks:
    - name: add key
      apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present
      
    - name: Get nvidia docker list file
      shell: curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list -o /etc/apt/sources.list.d/nvidia-docker.list 

    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install nvidia docker 
      apt:
        name: nvidia-container-toolkit

    - name: Restart docker daemon
      shell: systemctl restart docker
