---
- hosts: k8s_nodes 
  remote_user: root

  tasks:
    - name: Install some utils 
      apt:
        pkg:
          - htop
          - tree
          - curl
          - apt-transport-https 
          - ca-certificates 
          - software-properties-common 
          - nmon
        update_cache: yes
    
    - name: Setup docker repo keys
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present 

    - name: Update repositories 
      apt:
        update_cache: yes

    - name: Install docker-ce 
      apt:
        name: docker-ce

    - name: Change docker driver to systemd 
      shell: mkdir -p /etc/systemd/system/docker.service.d 

    - name: set daemon.json 
      shell: |
        echo '{
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "insecure-registries": {{ insecured_docker_registries }},
          "storage-driver": "overlay2"
        }' > /etc/docker/daemon.json 

    - name: change daemon.json permission
      shell: chmod 644 /etc/docker/daemon.json

    - name: restart docker
      shell: systemctl daemon-reload && systemctl restart docker
