---
- hosts: k8s_gpu_nodes 
  remote_user: root

  tasks:
    - name: add key
      apt_key:
        url: https://nvidia.github.io/nvidia-docker/gpgkey
        state: present
      
    - name: Get nvidia docker list file
      shell: curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list -o /etc/apt/sources.list.d/nvidia-docker.list 

    - name: Update apt cache
      apt:
        update_cache: yes
    
    - name: Install nvidia docker 
      apt:
        pkg:
          - nvidia-docker2
          - nvidia-container-runtime
          - nvidia-container-toolkit

    - name: Stop docker daemon 
      shell: systemctl stop docker 

    #- name: Configure docker daemon
    #  shell: sed -i "s/nvidia-container-runtime/\/usr\/bin\/nvidia-container-runtime/g" /etc/docker/daemon.json

    - name: Configure docker daemon 
      shell: |
        echo '{
          "default-runtime": "nvidia",
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "100m"
          },
          "insecure-registries": {{ insecured_docker_registries }},
          "storage-driver": "overlay2",
          "runtimes": {
            "nvidia": {
              "path": "/usr/bin/nvidia-container-runtime",
              "runtimeArgs": []
            }
          }
        }' > /etc/docker/daemon.json 

    - name: Add nvidia-docker check 
      shell: echo "docker run --runtime nvidia nvidia/cuda:10.0-base nvidia-smi" > /root/check-nvidia-docker.sh

    - name: Change permission of docker daemon.json
      shell: chmod 644 /etc/docker/daemon.json

    - name: Restart docker daemon
      shell: systemctl daemon-reload && systemctl start docker
