---
  - hosts: k8s_nodes 
    remote_user: root

    tasks: 
      - name: Append or update kernerl parameters
        ansible.builtin.blockinfile:
          path: /etc/sysctl.conf
          block: |
            net.bridge.bridge-nf-call-iptables=1
            vm.swappiness = 0

      - name: enable kernel parameters
        shell: sysctl -p;swapoff -a

      - name: set rc.local 
        shell: |
          echo "#!/bin/sh -e
          # Kubeadm 1.15 needs /dev/kmsg to be there, but it's not in lxc, but we can just use /dev/console instead
          # see: https://github.com/kubernetes-sigs/kind/issues/662
          if [ ! -e /dev/kmsg ]; then
            ln -s /dev/console /dev/kmsg
          fi
          mount --make-rshared /" > /etc/rc.local && chmod +x /etc/rc.local

      #- name: set kmsg ( Hack required to provision k8s v1.15+ in LXC containers )
      #  shell: mknod /dev/kmsg c 1 11

      #- name: set rc.local
      #  shell: |
      #    echo "#!/bin/sh -e
      #    mknod /dev/kmsg c 1 11 " > /etc/rc.local && chmod +x /etc/rc.local

  
  - hosts: proxmox
    remote_user: root 
  
    vars:
      id_list:
        - "{{ k8s_node0_id }}"
        - "{{ k8s_node1_id }}"
        - "{{ k8s_node2_id }}"
        - "{{ k8s_node3_id }}"
        
    ## Tweak lxc container to run k8s
    ## https://medium.com/@kvaps/run-kubernetes-in-lxc-container-f04aa94b6c9c 
    ## https://github.com/MarijnKoesen/kubernetes-in-proxmox-with-kubeadm-lxc-and-wireshark#step-1-prepare-the-proxmox-host
    tasks:
      - name: Append or update kernerl parameters
        ansible.builtin.blockinfile:
          path: /etc/sysctl.conf
          block: |
            net.netfilter.nf_conntrack_max = 131072
            net.nf_conntrack_max = 131072
            vm.swappiness = 0

      - name: enable kernel parameters
        shell: sysctl -p;swapoff -a

      #- name: Enabling the overlay kernel module on proxmox host
      #  shell: echo overlay >> /etc/modules

      - name: Configuring the overlay kernel module to be loaded on boot. 
        #lineinfile:
        #  path: /etc/modules 
        #  line: 'overlay'
        ansible.builtin.blockinfile:
          path: /etc/modules
          block: |
            overlay

      - name: Loading the overlay kernel module.
        modprobe: 
          name: overlay

      - name: Additional lxc config for k8s
        ansible.builtin.blockinfile:
          path: /etc/pve/lxc/{{ item }}.conf
          block: |
            echo "## Additional config for k8s
            lxc.apparmor.profile: unconfined
            lxc.cap.drop: 
            lxc.cgroup2.devices.allow: a
            lxc.mount.auto: "proc:rw sys:rw"
        with_items: "{{ id_list }}"

      - name: Stop containers 
        shell: pct stop {{ item }}
        with_items: "{{ id_list }}"

      - name: Wait for 5 secons while restart
        wait_for: timeout=5
      
      - name: Start containers 
        shell: pct start {{ item }}
        with_items: "{{ id_list }}"

      - name: Wait for 10 secons while restart
        wait_for: timeout=10


  - hosts: proxmox_other
    remote_user: root

    ## Tweak lxc container to run k8s
    ## https://medium.com/@kvaps/run-kubernetes-in-lxc-container-f04aa94b6c9c
    ## https://github.com/MarijnKoesen/kubernetes-in-proxmox-with-kubeadm-lxc-and-wireshark#step-1-prepare-the-proxmox-host
    tasks:
      - name: Append or update kernerl parameters
        ansible.builtin.blockinfile:
          path: /etc/sysctl.conf
          block: |
            net.netfilter.nf_conntrack_max = 131072
            net.nf_conntrack_max = 131072
            vm.swappiness = 0 

      - name: enable kernel parameters
        shell: sysctl -p;swapoff -a

      - name: Configuring the overlay kernel module to be loaded on boot.
        #lineinfile:
        #  path: /etc/modules
        #  line: 'overlay'
        ansible.builtin.blockinfile:
          path: /etc/modules
          block: |
            overlay

      - name: Loading the overlay kernel module.
        modprobe:
          name: overlay
