---
  - hosts: k8s_nodes 
    remote_user: root

    tasks: 
      - name: enable bridged traffic to iptable 
        shell: sysctl net.bridge.bridge-nf-call-iptables=1

      - name: set rc.local 
        shell: |
          echo "#!/bin/sh -e
          # Kubeadm 1.15 needs /dev/kmsg to be there, but it's not in lxc, but we can just use /dev/console instead
          # see: https://github.com/kubernetes-sigs/kind/issues/662
          if [ ! -e /dev/kmsg ]; then
            ln -s /dev/console /dev/kmsg
          fi
          mount --make-rshared /" > /etc/rc.local && chmod +x /etc/rc.local

  
  - hosts: proxmox
    remote_user: root 
  
    vars:
      id_list:
        - "{{ k8s_node0_id }}"
        - "{{ k8s_node1_id }}"
        - "{{ k8s_node2_id }}"
        
    ## Tweak lxc container to run k8s
    ## https://medium.com/@kvaps/run-kubernetes-in-lxc-container-f04aa94b6c9c 
    ## https://github.com/MarijnKoesen/kubernetes-in-proxmox-with-kubeadm-lxc-and-wireshark#step-1-prepare-the-proxmox-host
    tasks:
      - name: Enabling the overlay kernel module on proxmox host
        shell: echo overlay >> /etc/modules

      - name: Configuring the overlay kernel module to be loaded on boot. 
        lineinfile:
          path: /etc/modules 
          line: 'overlay'
      
      - name: Loading the overlay kernel module.
        modprobe: 
          name: overlay

      - name: Additional lxc config for k8s
        shell: |
          echo "## Additional config for k8s
          lxc.apparmor.profile: unconfined
          lxc.cap.drop: 
          lxc.cgroup.devices.allow: a
          lxc.mount.auto: proc:rw sys:rw
          " >> /etc/pve/lxc/{{ item }}.conf 
        with_items: "{{ id_list }}"

      - name: Stop containers 
        shell: pct stop {{ item }}
        with_items: "{{ id_list }}"

      - name: Wait for 5 secons while restart
        wait_for: timeout=5
      
      - name: Start containers 
        shell: pct start {{ item }}
        with_items: "{{ id_list }}"

      - name: Wait for 10 secons while restart
        wait_for: timeout=10
      
      