---
- hosts: k8s_master_node 
  remote_user: root 

  tasks:
    - name: Install Helm
      shell: curl -L {{ helm_url }} | bash
    
    - name: Add Flannel
      command: kubectl apply -f "{{ flannel_url }}"
      
    - name: Add device plugin
      command: kubectl apply -f "{{ nvidia_device_plugin }}"

    - name: copy ingress-nginx deploy yaml
      copy: 
        src: ./k8s/ingress-nginx-deploy.yaml
        dest: /root/ingress-nginx-deploy.yaml 

    - name: Add ingress nginx controller 
      command: kubectl apply -f /root/ingress-nginx-deploy.yaml
